version: '3'
services:
        web:
                image: flask_khn_v1
                build: .
                ports:
                        - "8887:8887"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
